// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// 
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
      // throw UnsupportedError(
      //   'DefaultFirebaseOptions have not been configured for web - '
      //   'you can reconfigure this by running the FlutterFire CLI again.',
      // );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        // return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDQ4KZE0tvMCzWVp02PN4NsbE5MVVGA_M',
    appId: '1:148035665678:web:bcca762e9365003d1c615f',
    messagingSenderId: '148035665678',
    projectId: 'postfix-ce6e0',
    storageBucket: 'postfix-ce6e0.appspot.com',
  );



      static const FirebaseOptions web =  FirebaseOptions(
        apiKey: "AIzaSyCDQ4KZE0tvMCzWVp02PN4NsbE5MVVGA_M", // Replace with your Firebase API key
        appId: "1:148035665678:web:bcca762e9365003d1c615f",  // Replace with your Firebase App ID
        projectId: "postfix-ce6e0",  // Replace with your Firebase Project ID
        storageBucket: "postfix-ce6e0.appspot.com", // Replace with your Firebase Storage Bucket
        messagingSenderId: "148035665678",  // Replace with your Firebase Messaging Sender ID
        authDomain: "postfix-ce6e0.firebaseapp.com",
        databaseURL: "https://postfix-ce6e0-default-rtdb.firebaseio.com",  // Replace with your Firebase Auth Domain
      );
  //   );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyC1B0rBw11_-h5vxb2UZqp8jW1sR7FS1D8',
  //   appId: '1:37394070573:ios:3801d7c8fd8c838dcb0ca4',
  //   messagingSenderId: '37394070573',
  //   projectId: 'wattreward-88d0a',
  //   storageBucket: 'wattreward-88d0a.appspot.com',
  //   androidClientId: '37394070573-n57nlcv59pesvfptu0kbljapn3gosica.apps.googleusercontent.com',
  //   iosClientId: '37394070573-8p9v73ak3sht1qf3kek0g7b160eiklig.apps.googleusercontent.com',
  //   iosBundleId: 'com.example.ev',
  // );
}